"""
Context & Memory Manager
========================
Lightweight in-memory state management layer for the investigation pipeline.
Responsible only for storing, updating, and retrieving session state.
"""
from __future__ import annotations

import uuid
from typing import Dict, Optional

from src.agent.entity_models import EntityExtractionResult
from src.agent.intent_models import IntentResult
from src.agent.memory_models import ContextMemory, InvestigationSession
from src.agent.pattern_models import PatternIdentificationResult
from src.agent.plan_models import ExecutionPlan
from src.agent.routing_models import RoutedPlan
from src.utils.logger import get_logger

logger = get_logger(__name__)


class SessionNotFoundError(Exception):
    """Raised when a requested session ID does not exist."""
    pass


class ContextMemoryManager:
    """
    Manages in-memory investigation sessions.
    Strictly isolated from intelligence, planning, or execution logic.
    """

    def __init__(self) -> None:
        self._store: Dict[str, ContextMemory] = {}

    def create_session(self, investigation_id: Optional[str] = None) -> str:
        """Creates a new investigation session and returns its ID."""
        session_id = str(uuid.uuid4())
        
        if session_id in self._store:
            # Technically highly unlikely with UUID4, but handled for completeness
            raise ValueError(f"Session {session_id} already exists.")
            
        session = InvestigationSession(
            session_id=session_id,
            investigation_id=investigation_id
        )
        self._store[session_id] = ContextMemory(session=session)
        logger.info("Created new ContextMemory session: %s", session_id)
        return session_id

    def get_session(self, session_id: str) -> ContextMemory:
        """Retrieves a session's ContextMemory object."""
        if session_id not in self._store:
            raise SessionNotFoundError(f"Session {session_id} not found.")
        return self._store[session_id]

    def get_context(self, session_id: str) -> ContextMemory:
        """Alias for get_session."""
        return self.get_session(session_id)

    def update_query(self, session_id: str, query: str) -> None:
        """Updates the conversation state with a new query."""
        ctx = self.get_session(session_id)
        ctx.conversation_state.add_query(query)
        ctx.touch()

    def store_intent(self, session_id: str, intent_result: IntentResult) -> None:
        """Stores the result of the Intent Recognition stage."""
        ctx = self.get_session(session_id)
        ctx.planning_state.intent_result = intent_result
        ctx.touch()

    def store_entities(self, session_id: str, entity_result: EntityExtractionResult) -> None:
        """Stores the result of the Entity Extraction stage."""
        ctx = self.get_session(session_id)
        ctx.planning_state.entity_result = entity_result
        ctx.touch()

    def store_pattern(self, session_id: str, pattern_result: PatternIdentificationResult) -> None:
        """Stores the result of the Pattern Identification stage."""
        ctx = self.get_session(session_id)
        ctx.planning_state.pattern_result = pattern_result
        ctx.touch()

    def store_execution_plan(self, session_id: str, plan: ExecutionPlan) -> None:
        """Stores the logical execution plan generated by the Dynamic Planner."""
        # Validate duplicate step IDs
        seen_steps = set()
        for step in plan.steps:
            if step.step_id in seen_steps:
                raise ValueError(f"Duplicate step ID found in execution plan: {step.step_id}")
            seen_steps.add(step.step_id)

        ctx = self.get_session(session_id)
        ctx.planning_state.execution_plan = plan
        
        # Populate initial pending steps from the plan
        ctx.execution_state.pending_steps = [step.step_id for step in plan.steps]
        ctx.touch()

    def store_routed_plan(self, session_id: str, routed_plan: RoutedPlan) -> None:
        """Stores the routed execution DAG generated by the Tool Router."""
        ctx = self.get_session(session_id)
        ctx.planning_state.routed_plan = routed_plan
        ctx.touch()

    def set_current_stage(self, session_id: str, stage_number: int) -> None:
        """Updates the current execution stage."""
        if stage_number < 0:
            raise ValueError(f"Stage number cannot be negative: {stage_number}")
        ctx = self.get_session(session_id)
        ctx.execution_state.current_stage = stage_number
        ctx.touch()

    def mark_step_completed(self, session_id: str, step_id: str) -> None:
        """Marks a specific step as successfully completed."""
        ctx = self.get_session(session_id)
        state = ctx.execution_state
        
        if step_id not in state.pending_steps and step_id not in state.failed_steps and step_id not in state.completed_steps:
            raise ValueError(f"Unknown step ID: {step_id}")
            
        if step_id in state.pending_steps:
            state.pending_steps.remove(step_id)
        if step_id in state.failed_steps:
            state.failed_steps.remove(step_id)
            
        if step_id not in state.completed_steps:
            state.completed_steps.append(step_id)
            
        ctx.touch()

    def mark_step_failed(self, session_id: str, step_id: str) -> None:
        """Marks a specific step as failed."""
        ctx = self.get_session(session_id)
        state = ctx.execution_state
        
        if step_id not in state.pending_steps and step_id not in state.completed_steps and step_id not in state.failed_steps:
            raise ValueError(f"Unknown step ID: {step_id}")

        if step_id in state.pending_steps:
            state.pending_steps.remove(step_id)
        if step_id in state.completed_steps:
            state.completed_steps.remove(step_id)
            
        if step_id not in state.failed_steps:
            state.failed_steps.append(step_id)
            
        ctx.touch()

    def clear_session(self, session_id: str) -> None:
        """Removes a session completely from memory."""
        if session_id not in self._store:
            raise SessionNotFoundError(f"Cannot clear non-existent session {session_id}.")
        del self._store[session_id]
        logger.info("Cleared ContextMemory session: %s", session_id)
