import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiService } from '../services/api';
import { StatusBadge, LoadingSpinner, ErrorState } from '../components/UIComponents';
import { Search, Filter, ChevronLeft, ChevronRight, Eye } from 'lucide-react';

export default function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // Filtering & Pagination
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedRisk, setSelectedRisk] = useState("All");

  useEffect(() => {
    const fetchAlerts = async () => {
      try {
        const res = await apiService.getAlerts();
        setAlerts(res.alerts);
      } catch (err) {
        setError("Failed to load alerts. Please try again.");
      } finally {
        setLoading(false);
      }
    };
    fetchAlerts();
  }, []);

  const filteredAlerts = alerts.filter(alert => {
    const matchesSearch = 
      alert.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      alert.customer.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesRisk = selectedRisk === "All" || alert.riskLevel === selectedRisk;

    return matchesSearch && matchesRisk;
  });

  if (loading) return <LoadingSpinner text="Loading alerts..." />;
  if (error) return <ErrorState title="Alerts Error" description={error} onRetry={() => window.location.reload()} />;

  return (
    <div className="p-6 lg:p-8 max-w-7xl mx-auto space-y-8 bg-slate-50 min-h-screen">
      
      {/* Header */}
      <div className="border-b border-slate-200 pb-4">
        <h1 className="text-2xl font-bold tracking-tight text-slate-900">Alerts</h1>
        <p className="text-sm text-slate-500 mt-1">Review suspicious transactions generated by the AML engine.</p>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
        
        {/* Toolbar: Search & Filters */}
        <div className="p-4 border-b border-slate-200 bg-white flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="relative max-w-md w-full">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
            <input 
              type="text" 
              placeholder="Search by Alert ID or Customer..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors"
            />
          </div>
          
          <div className="flex items-center gap-2">
            <Filter size={18} className="text-slate-400" />
            <select
              value={selectedRisk}
              onChange={(e) => setSelectedRisk(e.target.value)}
              className="pl-3 pr-8 py-2 border border-slate-300 rounded-lg text-sm bg-white focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 cursor-pointer"
            >
              <option value="All">All Risks</option>
              <option value="High">High</option>
              <option value="Medium">Medium</option>
              <option value="Low">Low</option>
            </select>
          </div>
        </div>

        {/* Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 uppercase bg-slate-50 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 font-semibold whitespace-nowrap">Alert ID</th>
                <th className="px-6 py-4 font-semibold whitespace-nowrap">Customer</th>
                <th className="px-6 py-4 font-semibold whitespace-nowrap">Risk Score</th>
                <th className="px-6 py-4 font-semibold whitespace-nowrap">Risk Level</th>
                <th className="px-6 py-4 font-semibold whitespace-nowrap">Status</th>
                <th className="px-6 py-4 font-semibold whitespace-nowrap">Created At</th>
                <th className="px-6 py-4 font-semibold whitespace-nowrap text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredAlerts.length > 0 ? (
                filteredAlerts.map((alert) => (
                  <tr key={alert.id} className="border-b border-slate-100 hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-4 font-medium text-slate-900 whitespace-nowrap">{alert.id}</td>
                    <td className="px-6 py-4 text-slate-700 whitespace-nowrap">{alert.customer}</td>
                    <td className="px-6 py-4 text-slate-700 font-medium">
                      <span className={alert.riskScore >= 80 ? 'text-red-600' : alert.riskScore >= 50 ? 'text-amber-600' : 'text-green-600'}>
                        {alert.riskScore}/100
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <StatusBadge status={alert.riskLevel} type="risk" />
                    </td>
                    <td className="px-6 py-4">
                      <StatusBadge status={alert.status} type="status" />
                    </td>
                    <td className="px-6 py-4 text-slate-500 whitespace-nowrap">
                      {new Date(alert.createdAt).toLocaleString(undefined, {
                        month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit'
                      })}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <Link 
                        to={`/investigation/${alert.id}`}
                        className="inline-flex items-center justify-center gap-1.5 px-3 py-1.5 bg-white border border-slate-200 text-sm font-medium text-blue-600 rounded-md hover:bg-blue-50 transition-colors shadow-sm"
                      >
                        <Eye size={16} /> View
                      </Link>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={7} className="px-6 py-16 text-center text-slate-500">
                    <div className="flex flex-col items-center justify-center space-y-2">
                      <Search size={32} className="text-slate-300" />
                      <p className="text-base font-medium text-slate-900">No alerts found.</p>
                      <p className="text-sm">We couldn't find any alerts matching your current filters.</p>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination Placeholder */}
        <div className="p-4 border-t border-slate-200 bg-white flex items-center justify-between">
          <span className="text-sm text-slate-500">
            Showing <span className="font-medium text-slate-900">{filteredAlerts.length}</span> of <span className="font-medium text-slate-900">{alerts.length}</span> alerts
          </span>
          <div className="flex items-center gap-2">
            <button 
              disabled
              className="p-1.5 border border-slate-200 text-slate-400 rounded hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronLeft size={18} />
            </button>
            <button 
              disabled
              className="p-1.5 border border-slate-200 text-slate-400 rounded hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronRight size={18} />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
